### ISSUE TITLE
Test Class: Recipe List

### ISSUE THREAD

**Issue by PaulHo0501** [CMPUT301F22T18/SnackNTrack#59]
## User Stories: 
[US 02.07.01](https://github.com/CMPUT301F22T18/SnackNTrack/issues/19)

## Description
As a developer, I want to have to test the functionality of the class Recipe List. Please write some unit tests for this purpose.

## Technical Requirement:
1. Use jUnit
2. Write a test for each of the function inside the class (each getter/setter, sorting function, add, edit and delete an element from the list)

## Acceptance Criteria:
- [ ] Sufficient tests
- [ ] Sufficient Documentation

**Comment by Purnapushkala** [comment]
#72
