### ISSUE TITLE
Project Part 2 Comments: Improve Story Boards

### ISSUE THREAD

**Issue by CharlotteTag** [CMPUT301F22T18/SnackNTrack#68]
## Description

Rework storyboards and mockups to line up with the TA's expectations

## Acceptance Criteria

- [x] Add interactions to mockups
- [x] Make mockups for each module
- [x] Each storyboard should stem from the MainActivity

**Comment by mark8m** [comment]
Finished work to meet criteria, as reflected in the [updated wiki page](https://github.com/CMPUT301F22T18/SnackNTrack/wiki/User-Interface-Mock-ups-and-Storyboard)
